### ISSUE TITLE
Skulls and banners sometimes lose their data

### ISSUE THREAD

**Issue by Folas1337** [Meta-Union/Meta-Union#32]
According to several reports, on both creative and builders it can happen that, supposedly for no reason, skulls as well as banners (and potentially all block entities) can lose their data and turn into plain banners or Steve heads. 

Further investigation is needed if this might be related to WorldEdit.

**Comment by Blazer28** [comment]
After testing, I was able to recreate the bug. It appears skulls and banners only lose data when worldedit is used within that chunk. T0psy later helped me try to recreate it, and whatever she placed was not losing it's data. I then considered that it could be one of my axiom features. After turning off the feature called "freeze block updates", and placing the banners again, I was not able to recreate the bug. I'm guessing the freeze block updates means it doesn't update the block data when you place it? So it shows visually until the chunk is "reloaded" by using worldedit on it?

The clip I recorded is too big to attach here, so here is a dropbox link: https://www.dropbox.com/scl/fi/d3zysr4jgbcwlk74qt959/Minecraft_-1.21-Multiplayer-3rd-party-Server-2024-07-21-20-31-33.mp4?rlkey=au4e1hvby7jmcgm6q9em3a4u7&st=ppnp7u0l&dl=0

**Comment by Folas1337** [comment]
We basically proved that it's gotta be Axiom as I can place skulls fine but Beef gets the same one, has the Freeze Block Updates in Axiom turned on and it will turn into a Steve skull as he places it.

If he turns it off, that problem is gone. My guess is that Axiom doesn't store every (or any) data of skull block entities but that's just a guess.

@Blazer28 Is going to get in touch with Axiom and we'll see what comes of it.
For now I'm marking this issue as "currentlyBlocked" until we hear back from you OR I'd personally like it even better if a GitHub issue on Axiom could be opened and linked here (by simple mentioning it in the comments). Then I could also follow it and keep track.

**Comment by Blazer28** [comment]
![image](https://github.com/user-attachments/assets/97240ded-370e-4c87-8d5e-c616feade75d)

**Comment by Folas1337** [comment]
It seems like this was fixed in version 4 of Axiom so we're closing this ticket/issue.
