### ISSUE TITLE
builder application switch link to the right link

### ISSUE THREAD

**Issue by ZickeLena** [Meta-Union/Meta-Union#34]
"#rules_and_info" on the builder application has to be changed into "FAQ" from the "info_center" :)

**Comment by Folas1337** [comment]
It seems I'm getting some random "context canceled" message when trying to change it. 

I'll try to make it from scratch to see if that'll fix it. But that'll be a couple hours until I get around to it.

**Comment by Folas1337** [comment]
Link has been updated.

Note to self:
1. The bot is open source, I just kind of forgot and it all falls under this GitHub organization: https://github.com/TicketsBot
2. They don't seem to be using the Issues feature over there which is a bummer cause then I can't keep track of the issue and can only pray it'll be resolved soon.
3. However I can watch the code commits but that's tedious and I might not do it... end of story
