### ISSUE TITLE
Should netdata be open to the public?

### ISSUE THREAD

**Issue by rasmussehlin** [Meta-Union/Meta-Union#51]
Hi,
I stumbled upon your Minecraft server homepage. I checked out the links to Netdata and I'm just wondering if that should be publicly available.
![Screenshot_20240824_090420_Firefox.jpg](https://github.com/user-attachments/assets/cf7bd4d7-9d61-4a9e-a8f6-f45a1683e30c)

That page looks like I control *something*. I have no idea how netdata works, I just wanted to alert you to any potential risks 😊

**Comment by Folas1337** [comment]
Dang, I am more than surprised by the fact you even used this GitHub issue tracker.
However you are right and they even warn about it... I was considering another solution or to do something about it but I haven't bothered yet.

I shall give it another look, thanks for telling me about it :)

**Comment by Folas1337** [comment]
One thing that makes it slightly less dangerous sounding is this from NetData themselves: <https://learn.netdata.cloud/docs/netdata-agent/securing-netdata-agents/:

It means there is very little you can do but it's not impossible. While I keep the container up to date, it doesn't mean it's not **an** attack vector. I just thought it'd be cool information for people that are playing on the Minecraft server and want to know what causes lag if there is any but perhaps it was a little "too well-intended" 😅 

I'll investigate what options I have to secure it to a level that seems about right :)

**Comment by Folas1337** [comment]
I have an idea: I'll use https://github.com/MauriceNino/dashdot publicly and only use NetData internally. Dashdot doesn't expose as much information and I can still use NetData for a kind of drilldown approach :)

**Comment by Folas1337** [comment]
This was definitely the last little nudge I needed to actually make the switch. NetData now runs on the VPN only, so only I can access it and dashdot has replaced the public facing information: <https://dashdot2.meta-union.com/> as well as <https://dashdot3.meta-union.com/>

Thanks you once again for this hint, this should resolve the "issue" 💛

**Comment by rasmussehlin** [comment]
Dang! You work fast! 😁

Glad I could give you a helping nudge.

**Comment by Folas1337** [comment]
> Dang! You work fast! 😁
Well thank you. I've been considering it for a while and actually had a couple candidates to use in mind already, just really had to make the decision which one to pick.

I just want to impress myself by how fast one could potentially get something done. Some might say I'm a pretty competitive person but only if I feel like it's important and if I make it a challenge to myself.

**Comment by rasmussehlin** [comment]
This will be of topic for this issue, but, how many players do you usually have on your server? Are you running it as a hobby or is it part of your income?

**Comment by Folas1337** [comment]
> This will be of topic for this issue, but, how many players do you usually have on your server? Are you running it as a hobby or is it part of your income?

I mean the issue is closed, nobody cares hahaha 

Entirely my hobby, currently getting 10-14 players at peak times. It's not much but I'm proud of it :)

**Comment by rasmussehlin** [comment]
I think it's pretty cool! I'm a bit surprised you don't get more players, everything seems pretty well packaged. Anyway, cool project 😁

**Comment by Folas1337** [comment]
I'd say the main reason is because I don't put anything into marketing. Only word of mouth and bumping on forums every now and then :sweat_smile: 

Thanks for some more kind words though, I really appreciate it! :smile:
