### ISSUE TITLE
Repeating reminders/hints

### ISSUE THREAD

**Issue by Folas1337** [Meta-Union/Meta-Union#66]
Send a message in chat every hour. One each hour. 

Here's my current list, more might be added while this ticket is open and afterwards (although then just in game, not in this ticket).

- You can use '/menu' to open a GUI with all functionality of the server you're playing
- Meta-Union costs around $130 every month. If you love Meta-Union you can support us on '/vip'
- Did you ever want an overview of the whole world you're playing on and see where everyone is? Check out '/map'
- Want to report someone to the staff team? Head over to '/discord's and open a ticket. It'll only be visible to staff and handled with discretion

Note to self: Try implementing it with Skript so I don't need another plugin :)

**Comment by MRollin03** [comment]
By the means of one message per hour would that mean that each message would be displayed 6 times per day. 24/4 = 6.

Or is it one each 15min?

**Comment by Folas1337** [comment]
It's been created and already added to the repo here: https://github.com/Meta-Union/Meta-Union/blob/main/mc1/lobby1/plugins/Skript/scripts/1HourLoop.sk

More messages might be added in the future, for now this shall suffice :)
